name: sqlhandler
version: '0.1.0.0'
author: Grant Weyburne
maintainer: gbwey9@gmail.com
license: BSD3
dependencies:
- base
- bytestring
- containers
- contravariant
- foldl
- Frames >= 0.6.1
- generics-sop
- hdbc-odbc2
- lens
- mtl
- one-liner
- profunctors
- safe
- shakespeare
- table-layout == 0.9.0.0
- text
- these >= 1.0.0
- time
- typelevel
- vinyl >= 0.10.0.1
- predicate-typed

default-extensions: []
library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
#  - -fomit-interface-pragmas
  when:
     condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie


tests:
  spec:
    main: "Spec.hs"
    ghc-options:
    - -threaded
    - -O0
#    - -fomit-interface-pragmas
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
    source-dirs:
      - test
#      - src
    dependencies:
      - sqlhandler
      - pipes
      - hspec
      - QuickCheck
      - should-not-typecheck
      - deepseq
      - tasty-hunit
      - tasty-quickcheck
      - tasty
      - generic-lens

data-files: []
