resolver: lts-18.10
packages:
- '.'
extra-deps:
- Frames-0.7.2
- discrimination-0.4.1
- ../coreutils
- ../docutils
- ../hdbc-odbc2
- ../table-layout

# ghc-options:
#  "$locals": -fwrite-ide-info
#  "$everything": -haddock
