flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../hdbc
  extra-dep: true
- location: ../predicate
  extra-dep: true
- location: ../predicate-typed
  extra-dep: true
- location: ../table-layout
  extra-dep: true
- location: ../typelevel
  extra-dep: true
extra-deps:
- pretty-terminal-0.1.0.0
- tree-view-0.5
- Frames-0.6.1
- discrimination-0.4
- symbols-0.3.0.0
- these-lens-1
arch: x86_64
resolver: lts-14.10

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}