resolver: lts-17.0
packages:
- '.'
extra-deps:
- pretty-terminal-0.1.0.0
- Frames-0.7.0
- discrimination-0.4
- symbols-0.3.0.0
- ../hdbc-odbc2
- ../predicate-typed
- ../table-layout
- ../typelevel

ghc-options:
  "$locals": -fwrite-ide-info
  "$everything": -haddock
